### ISSUE TITLE
请问怎么用蓝牙LinuxBluez模拟NintendoSwitch的Pro手柄

### ISSUE THREAD

**Issue by rayPopo** [mumumusuc/Bluetooth-Joycon#1]
你好，我看到README中介绍了用bluez模拟pro手柄的部分，但是介绍的太简单，可否详细说明一些，谢谢！

**Comment by mumumusuc** [comment]
因为我不会bluez编程:sweat_smile:
我也没找到bluez靠谱的例子或者教程，靠dbus那套写了写确实能用，理论验证成功了，b站也上传了演示视频。
你要是懂得bluez编程的话，就把我给的sdp信息注册到bluez服务，并且禁用其它所有Linux自启的蓝牙服务，只有这样NS才会主动连接你的设备，当然也欢迎帮忙继续完善这部分工作！
晚些时候会上传之前写的demo，希望能有所帮助吧。

**Comment by rayPopo** [comment]
非常感谢！

**Comment by rayPopo** [comment]
期待你的demp

**Comment by mumumusuc** [comment]
> 期待你的demp

上传到了release：bt-test.zip

**Comment by rayPopo** [comment]
非常感谢！

**Comment by mumumusuc** [comment]
bluez相关内容被我分离到了这个[项目](https://github.com/mumumusuc/bluez-ns-controller)，有什么问题的话可以去那里讨论，这个我关闭了。
